
---
- hosts: localhost
  connection: local
  become: True
  gather_facts: True

  vars_files:
    - vars.txt

  pre_tasks:
    - name: Check if vars.txt exists
      stat:
        path: ./vars.txt
      register: vars_file

    - name: Fail if vars.txt is missing
      fail:
        msg: |
          "vars.txt not found!
           Please copy vars.txt.example to vars.txt and edit it with your values."
      when: not vars_file.stat.exists

  roles:
    - VPS
